spark:
  app_name: "BTC Price Z-Score Loader"
  packages:
    - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0"
    - "org.mongodb.spark:mongo-spark-connector_2.12:3.0.2"
  repositories:
    - "https://repo1.maven.org/maven2"
    - "https://dl.bintray.com/spark-packages/maven"
  configs:
    spark.sql.streaming.checkpointLocation: "/tmp/checkpoint"
    spark.sql.shuffle.partitions: 2
    spark.sql.streaming.schemaInference: "true"
    spark.sql.streaming.forceDeleteTempCheckpointLocation: "true"
    spark.sql.streaming.stateStore.providerClass: "org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider"
